version: "3.7"
services:
   nodeapp:
     build: .
     container_name: nodejs_testapp
   nginx:
     image: nginx:alpine
     container_name: nginx_test
     restart: unless-stopped
     ports:
       - "80:80"
     volumes:
       - ./vol/nginx/nginx.conf:/etc/nginx/nginx.conf # nginx 설정 파일 volume 맵핑
    
